<?php
function paja_course_price_permission() {
  return array(
    'Paja course price extra values' => array(
        'title' => t('Permission to set extra values in course calculator.'),
        'description' => t('Permission to set extra values in course calculator like profit margin.'),
    ),
  );
}

function paja_course_price_field_info() {
  return array(
    'paja_course_price' => array(
      'label' => t('Course price calculator'),
      'description' => t("This field stores your course price"),
      'settings' => array('allowed_values' => array(), 'allowed_values_function' => ''),
      'default_widget' => 'paja_course_price_field',
      'default_formatter' => 'paja_course_price_default',
    ),
  );
}

function paja_course_price_field_widget_info() {
  return array(
    'paja_course_price_field' => array(
      'label' => t('Paja course price widget'),
      'field types' => array('paja_course_price'),
    ),
  );
}

/**
* Implements hook_field_settings_form().
*/
function paja_course_price_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];
  // Add your global settings fields here
  $form = array();
  return $form;
}


function paja_course_price_field_is_empty($item, $field) {
  if (!isset($item['paja_course_price']['standard_fields']['instructor_fee'])) {
    return TRUE;
  }elseif (!isset($item['paja_course_price']['standard_fields']['distance_days'])) {
    return TRUE;
  }elseif (!isset($item['paja_course_price']['standard_fields']['local_days'])) {
    return TRUE;
  }elseif (!isset($item['paja_course_price']['standard_fields']['attendees_min'])) {
    return TRUE;
  }elseif (!isset($item['paja_course_price']['standard_fields']['attendees_max'])) {
    return TRUE;
  }elseif (!isset($item['paja_course_price']['standard_fields']['miscellanous_costs'])) {
    return TRUE;
  }elseif (!isset($item['paja_course_price']['standard_fields']['price'])) {
    return TRUE;
  }elseif (!isset($item['paja_course_price']['extra_fields']['profit_margin'])) {
    return TRUE;
  }elseif (!isset($item['paja_course_price']['extra_fields']['premises_costs_per_day'])) {
    return TRUE;
  }elseif (!isset($item['paja_course_price']['extra_fields']['management_costs_per_attendee'])) {
    return TRUE;
  }
  return FALSE;
}

/**
* Implements hook_field_validate().
*/
function paja_course_price_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  // Loop through field items in the case of multiple values.
//   foreach ($items as $delta => $item) {
//     if (isset($item['jotain']) && $item['jotain'] != '') {
//       if (!valid_license_plate($item['jotain'])) {
//         $errors[$field['field_name']][$langcode][$delta][] = array(
//             'error' => t('Virhe!'),
//         );
//       }
//     }
//   }
}

/**
* Implements hook_field_widget_form().
*/
function paja_course_price_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $path = drupal_get_path('module', 'paja_course_price');
  $element['#attached']['css'][] = "$path/paja_course_price.css";
  $element['#attached']['js'][] = "$path/paja_course_price.js";
  switch ($instance['widget']['type']) {
    case 'paja_course_price_field' :     
      $element['paja_course_price'] = array(
        '#type' => 'fieldset',
        '#title' => '',
//         '#attached' => array(
//             'css' => array(drupal_get_path('module', 'paja_course_price') . '/paja_course_price.css'),
//             'js' => array(drupal_get_path('module', 'paja_course_price') . '/paja_course_price.js'),
//         ),
        '#prefix' => '<div id="paja-course-wrapper">',
        '#suffix' => '</div>',
        '#tree' => TRUE,
      );
      $profit_margin = isset($items[$delta]['profit_margin']) ? $items[$delta]['profit_margin'] : 500;
      $premises_costs_per_day = isset($items[$delta]['premises_costs_per_day']) ? $items[$delta]['premises_costs_per_day'] : 250;
      $management_costs_per_attendee = isset($items[$delta]['management_costs_per_attendee']) ? $items[$delta]['management_costs_per_attendee'] : 25;
      $vo_per_local_attendee = isset($items[$delta]['vo_per_local_attendee']) ? $items[$delta]['vo_per_local_attendee'] : 152;
      if(user_access('Paja course price extra values')){
        $element['paja_course_price']['extra_fields'] = array(
          '#type' => 'fieldset',
          '#title' => 'Kate ja hallinnolliset kulut',
          '#prefix' => '<div id="paja-course-extra-field-wrapper">',
          '#suffix' => '</div>',
          '#collapsible' => TRUE,
          '#collapsed' => TRUE,
          '#tree' => TRUE,
        );
        $element['paja_course_price']['extra_fields']['profit_margin'] = array(
          '#type' => 'rangefield',
          '#min' => 0,
          '#max' => 1000,
          '#title' => t('Kate'),
          '#prefix' => '<div id="paja-course-profit-margin" class="paja-course-price-range-field">',
          '#suffix' => '</div>',
          '#default_value' => $profit_margin,
          '#required' => false,
        );
        $element['paja_course_price']['extra_fields']['profit_margin_number_field'] = array(
          '#type' => 'numberfield',
          '#min' => 0,
          '#max' => 1000,
          '#prefix' => '<div id="paja-course-profit-margin-number" class="paja-course-price-number-field">',
          '#suffix' => '</div>',
          '#default_value' => $profit_margin,
        );
        $element['paja_course_price']['extra_fields']['premises_costs_per_day'] = array(
          '#type' => 'rangefield',
          '#min' => 0,
          '#max' => 1000,
          '#title' => t('Tilojen kulut päivältä'),
          '#prefix' => '<div id="paja-course-premises-costs-per-day" class="paja-course-price-range-field">',
          '#suffix' => '</div>',
          '#default_value' => $premises_costs_per_day,
          '#required' => false,
        );
        $element['paja_course_price']['extra_fields']['premises_costs_per_day_number_field'] = array(
          '#type' => 'numberfield',
          '#min' => 0,
          '#max' => 1000,
          '#prefix' => '<div id="paja-course-premises-costs-per-day-number" class="paja-course-price-number-field">',
          '#suffix' => '</div>',
          '#default_value' => $premises_costs_per_day,
        );
        $element['paja_course_price']['extra_fields']['management_costs_per_attendee'] = array(
          '#type' => 'rangefield',
          '#min' => 0,
          '#max' => 1000,
          '#title' => t('Hallinnointi kulut henkilöa kohden'),
          '#prefix' => '<div id="paja-course-management-costs-per-attendee" class="paja-course-price-range-field">',
          '#suffix' => '</div>',
          '#default_value' => $management_costs_per_attendee,
          '#required' => false,
        );
        $element['paja_course_price']['extra_fields']['management_costs_per_attendee_number_field'] = array(
          '#type' => 'numberfield',
          '#min' => 0,
          '#max' => 1000,
          '#prefix' => '<div id="paja-course-management-costs-per-attendee-number" class="paja-course-price-number-field">',
          '#suffix' => '</div>',
          '#default_value' => $management_costs_per_attendee,
        );
      }

      drupal_add_js(array('paja_course_price' => array('profitMargin' => $profit_margin)), 'setting');
      drupal_add_js(array('paja_course_price' => array('premisesCostsPerDay' => $premises_costs_per_day)), 'setting');
      drupal_add_js(array('paja_course_price' => array('managementCostsPerAttendee' => $management_costs_per_attendee)), 'setting');
      drupal_add_js(array('paja_course_price' => array('voPerLocalAttendee' => $vo_per_local_attendee)), 'setting');
      
      $element['paja_course_price']['standard_fields'] = array(
        '#type' => 'fieldset',
        '#title' => 'Kurssilaskuri',
        '#prefix' => '<div id="paja-course-calculon">',
        '#suffix' => '</div>',
        '#tree' => TRUE,
      );
      
      $element['paja_course_price']['standard_fields']['instructor_fee'] = array(
        '#type' => 'rangefield',
        '#min' => 0,
        '#max' => 10000,
        '#title' => t('Vetäjien palkkiot'),
        '#prefix' => '<div id="paja-course-instructor-fee" class="paja-course-price-range-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['instructor_fee']) ? $items[$delta]['instructor_fee'] : '5',
        '#required' => $element['#required'],
      );
      $element['paja_course_price']['standard_fields']['instructor_fee_number_field'] = array(
        '#type' => 'numberfield',
        '#min' => 0,
        '#max' => 10000,
        '#prefix' => '<div id="paja-course-instructor-fee-number" class="paja-course-price-number-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['instructor_fee']) ? $items[$delta]['instructor_fee'] : '5',
      );
      
      $element['paja_course_price']['standard_fields']['distance_days'] = array(
        '#type' => 'rangefield',
        '#min' => 0,
        '#max' => 255,
        '#title' => t('Etäpäivät'),
        '#prefix' => '<div id="paja-course-distance-days" class="paja-course-price-range-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['distance_days']) ? $items[$delta]['distance_days'] : '5',
        '#required' => $element['#required'],
      );
      $element['paja_course_price']['standard_fields']['distance_days_number_field'] = array(
        '#type' => 'numberfield',
        '#min' => 0,
        '#max' => 255,
        '#prefix' => '<div id="paja-course-distance-days-number" class="paja-course-price-number-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['distance_days']) ? $items[$delta]['distance_days'] : '5',
      );
      
      $element['paja_course_price']['standard_fields']['local_days'] = array(
        '#type' => 'rangefield',
        '#min' => 0,
        '#max' => 255,
        '#title' => t('Lähipäivät'),
        '#prefix' => '<div id="paja-course-local-days" class="paja-course-price-range-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['local_days']) ? $items[$delta]['local_days'] : '5',
        '#required' => $element['#required'],
      );
      $element['paja_course_price']['standard_fields']['local_days_number_field'] = array(
        '#type' => 'numberfield',
        '#min' => 0,
        '#max' => 255,
        '#prefix' => '<div id="paja-course-local-days-number" class="paja-course-price-number-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['local_days']) ? $items[$delta]['local_days'] : '5',
      );
      
      $element['paja_course_price']['standard_fields']['attendees_min'] = array(
        '#type' => 'rangefield',
        '#min' => 0,
        '#max' => 255,
        '#prefix' => '<div id="paja-course-attendees-min" class="paja-course-price-range-field">',
        '#suffix' => '</div>',
        '#title' => t('Osallistujamäärä, jolla kurssi toteutuu'),
        '#default_value' => isset($items[$delta]['attendees_min']) ? $items[$delta]['attendees_min'] : '5',
        '#required' => $element['#required'],
      );
      $element['paja_course_price']['standard_fields']['attendees_min_number_field'] = array(
        '#type' => 'numberfield',
        '#min' => 0,
        '#max' => 255,
        '#prefix' => '<div id="paja-course-attendees-min-number" class="paja-course-price-number-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['attendees_min']) ? $items[$delta]['attendees_min'] : '5',
      );
      
      $element['paja_course_price']['standard_fields']['attendees_max'] = array(
        '#type' => 'rangefield',
        '#min' => 0,
        '#max' => 255,
        '#prefix' => '<div id="paja-course-attendees-max" class="paja-course-price-range-field">',
        '#suffix' => '</div>',
        '#title' => t('Suurin mahdollinen osallistujamäärä kurssille'),
        '#default_value' => isset($items[$delta]['attendees_max']) ? $items[$delta]['attendees_max'] : '5',
        '#required' => $element['#required'],
      );
      $element['paja_course_price']['standard_fields']['attendees_max_number_field'] = array(
        '#type' => 'numberfield',
        '#min' => 0,
        '#max' => 255,
        '#prefix' => '<div id="paja-course-attendees-max-number" class="paja-course-price-number-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['attendees_max']) ? $items[$delta]['attendees_max'] : '5',
      );
      
      $element['paja_course_price']['standard_fields']['miscellanous_costs'] = array(
        '#type' => 'rangefield',
        '#min' => 0,
        '#max' => 10000,
        '#prefix' => '<div id="paja-course-miscellanous-costs" class="paja-course-price-range-field">',
        '#suffix' => '</div>',
        '#title' => t('Muut kulut'),
        '#default_value' => isset($items[$delta]['miscellanous_costs']) ? $items[$delta]['miscellanous_costs'] : '5',
        '#required' => $element['#required'],
      );
      $element['paja_course_price']['standard_fields']['miscellanous_costs_number_field'] = array(
        '#type' => 'numberfield',
        '#min' => 0,
        '#max' => 10000,
        '#prefix' => '<div id="paja-course-miscellanous-costs-number" class="paja-course-price-number-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['miscellanous_costs']) ? $items[$delta]['miscellanous_costs'] : '5',
      );
      
      $element['paja_course_price']['standard_fields']['price'] = array(
        '#type' => 'rangefield',
        '#min' => 0,
        '#max' => 2000,
        '#prefix' => '<div id="paja-course-price" class="paja-course-price-range-field">',
        '#suffix' => '</div>',
        '#title' => t('Kurssimaksu'),
        '#default_value' => isset($items[$delta]['price']) ? $items[$delta]['price'] : '5',
        '#required' => $element['#required'],
      );
      
      $element['paja_course_price']['standard_fields']['price_number_field'] = array(
        '#type' => 'numberfield',
        '#min' => 0,
        '#max' => 2000,
        '#prefix' => '<div id="paja-course-price-number" class="paja-course-price-number-field">',
        '#suffix' => '</div>',
        '#default_value' => isset($items[$delta]['price']) ? $items[$delta]['price'] : '5',
      );
      
      $element['paja_course_price']['table'] = array(
        '#title' => t(''),
        '#prefix' => '<div id="paja-course-table">',
      	'#suffix' => '</div>',
      );
      
      $element['paja_course_price']['result'] = array(
        '#title' => t(''),
        '#prefix' => '<div id="paja-course-result">',
        '#suffix' => '</div>',
      );
      
      break;
  }
  return $element;
}

/**
* Implements hook_field_presave().
*/
function paja_course_price_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  foreach ($items as $delta => $item) {
    $items[$delta]['profit_margin'] = $item['paja_course_price']['extra_fields']['profit_margin'];
    $items[$delta]['premises_costs_per_day'] = $item['paja_course_price']['extra_fields']['premises_costs_per_day'];
    $items[$delta]['management_costs_per_attendee'] = $item['paja_course_price']['extra_fields']['management_costs_per_attendee'];
    $items[$delta]['instructor_fee'] = $item['paja_course_price']['standard_fields']['instructor_fee'];
    $items[$delta]['distance_days'] = $item['paja_course_price']['standard_fields']['distance_days'];
    $items[$delta]['local_days'] = $item['paja_course_price']['standard_fields']['local_days'];
    $items[$delta]['attendees_min'] = $item['paja_course_price']['standard_fields']['attendees_min'];
    $items[$delta]['attendees_max'] = $item['paja_course_price']['standard_fields']['attendees_max'];
    $items[$delta]['miscellanous_costs'] = $item['paja_course_price']['standard_fields']['miscellanous_costs'];
    $items[$delta]['price'] = $item['paja_course_price']['standard_fields']['price'];
  }
}

/**
* Implements hook_field_formatter_info().
*/
function paja_course_price_field_formatter_info() {
  return array(
    'paja_course_price_default' => array(
      'label' => t('Price'),
      'field types' => array('paja_course_price'),
    ),
    'paja_course_price_mini_panel' => array(
      'label' => t('Price mini panel hack'),
      'field types' => array('paja_course_price'),
    ),
    'paja_course_price_attendees_min' => array(
      'label' => t('Min attendees'),
      'field types' => array('paja_course_price'),
    ),
    'paja_course_price_attendees_max' => array(
      'label' => t('Max attendees'),
      'field types' => array('paja_course_price'),
    ),
  );
}

/**
* Implements hook_field_formatter_view().
*/
function paja_course_price_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'paja_course_price_default' :
      foreach ($items as $delta => $item) {
        if (isset($item['price'])) {
          $element[$delta]['#markup'] = $item['price'] . "€";
        }
      }
    break;
    case 'paja_course_price_attendees_min' :
      foreach ($items as $delta => $item) {
        if (isset($item['attendees_min'])) {
          $element[$delta]['#markup'] = $item['attendees_min'];
        }
      }
    break;
    case 'paja_course_price_attendees_max' :
      foreach ($items as $delta => $item) {
        if (isset($item['attendees_max'])) {
          $element[$delta]['#markup'] = $item['attendees_max'];
        }
      }
    break;
    case 'paja_course_price_mini_panel' :
    foreach ($items as $delta => $item) {
      if (isset($item['price'])) {
        $element[$delta]['#markup'] = '<div class="field-label">Hinta:&nbsp;</div>' . $item['price'] . "€";
      }
    }
    break;
  }
  return $element;
}

